const mainFunctions = require("./main");

module.exports = {
  // main Database
  // Loan Db Object
  dbGetLoan: mainFunctions.dbGetLoan,
  dbCreateLoan: mainFunctions.dbCreateLoan,
  dbUpdateLoan: mainFunctions.dbUpdateLoan,
  dbDeleteLoan: mainFunctions.dbDeleteLoan,
  dbListLoans: mainFunctions.dbListLoans,
  createLoan: mainFunctions.createLoan,
  getIdListOfLoanByField: mainFunctions.getIdListOfLoanByField,
  getLoanById: mainFunctions.getLoanById,
  getLoanAggById: mainFunctions.getLoanAggById,
  getLoanListByQuery: mainFunctions.getLoanListByQuery,
  getLoanStatsByQuery: mainFunctions.getLoanStatsByQuery,
  getLoanByQuery: mainFunctions.getLoanByQuery,
  updateLoanById: mainFunctions.updateLoanById,
  updateLoanByIdList: mainFunctions.updateLoanByIdList,
  updateLoanByQuery: mainFunctions.updateLoanByQuery,
  deleteLoanById: mainFunctions.deleteLoanById,
  deleteLoanByQuery: mainFunctions.deleteLoanByQuery,

  // Reservation Db Object
  dbGetReservation: mainFunctions.dbGetReservation,
  dbCreateReservation: mainFunctions.dbCreateReservation,
  dbUpdateReservation: mainFunctions.dbUpdateReservation,
  dbDeleteReservation: mainFunctions.dbDeleteReservation,
  dbListReservations: mainFunctions.dbListReservations,
  createReservation: mainFunctions.createReservation,
  getIdListOfReservationByField: mainFunctions.getIdListOfReservationByField,
  getReservationById: mainFunctions.getReservationById,
  getReservationAggById: mainFunctions.getReservationAggById,
  getReservationListByQuery: mainFunctions.getReservationListByQuery,
  getReservationStatsByQuery: mainFunctions.getReservationStatsByQuery,
  getReservationByQuery: mainFunctions.getReservationByQuery,
  updateReservationById: mainFunctions.updateReservationById,
  updateReservationByIdList: mainFunctions.updateReservationByIdList,
  updateReservationByQuery: mainFunctions.updateReservationByQuery,
  deleteReservationById: mainFunctions.deleteReservationById,
  deleteReservationByQuery: mainFunctions.deleteReservationByQuery,

  // LoanEvent Db Object
  dbGetLoanevent: mainFunctions.dbGetLoanevent,
  dbCreateLoanevent: mainFunctions.dbCreateLoanevent,
  dbUpdateLoanevent: mainFunctions.dbUpdateLoanevent,
  dbDeleteLoanevent: mainFunctions.dbDeleteLoanevent,
  dbListLoanevents: mainFunctions.dbListLoanevents,
  createLoanEvent: mainFunctions.createLoanEvent,
  getIdListOfLoanEventByField: mainFunctions.getIdListOfLoanEventByField,
  getLoanEventById: mainFunctions.getLoanEventById,
  getLoanEventAggById: mainFunctions.getLoanEventAggById,
  getLoanEventListByQuery: mainFunctions.getLoanEventListByQuery,
  getLoanEventStatsByQuery: mainFunctions.getLoanEventStatsByQuery,
  getLoanEventByQuery: mainFunctions.getLoanEventByQuery,
  updateLoanEventById: mainFunctions.updateLoanEventById,
  updateLoanEventByIdList: mainFunctions.updateLoanEventByIdList,
  updateLoanEventByQuery: mainFunctions.updateLoanEventByQuery,
  deleteLoanEventById: mainFunctions.deleteLoanEventById,
  deleteLoanEventByQuery: mainFunctions.deleteLoanEventByQuery,
};
